version: '3.8'

services:
  sendgrid-forwarder:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sendgrid-forwarder2
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    env_file:
      - .env